version: 2

sources:
  - name: chainwalkers
    schema: bronze_chainwalkers
    database: flipside
    tables:
      - name: harmony_blocks
        description: "Blocks from the Harmony chain. Note always use the latest block by ingested at timestamp as duplicates can exist in this table!"
        columns:
          - name: offset_id
            description: Synonmous with block_id for Harmony
          - name: block_id
            description: The height of the chain this block corresponds with
          - name: block_timestamp
            description: The time the block was minted
          - name: network
            description: The blockchain network (i.e. mainnet, testnet, etc.)
          - name: chain_id
            description: Synonmous with blockchain name for Harmony
          - name: tx_count
            description: The number of transactions in the block
          - name: header
            description: A json column containing the blocks header information
          - name: txs
            description: An array of json objects containing each tx and decoded logs
          - name: ingested_at
            description: The time this data was ingested into the table by Snowflake

